### ISSUE TITLE
Can't colorize 'unread' tabs anymore

### ISSUE THREAD

**Issue by Brandhand** [Aris-t2/CustomCSSforFx#129]
When enabling the import urls:
./config/custom_tab_color_settings.css 
./config/custom_tab_text_settings.css 

unread tabs are not colorized accordingly.

I found a solution on Reddit
https://www.reddit.com/r/FirefoxCSS/comments/8iglk7/unread_tabs_selection_not_possible_in_firefox_61/

**Comment by Aris-t2** [comment]
There is no **notselectedsinceload** tab state,
.tabbrowser-tab[notselectedsinceload] won't work.

**Comment by Brandhand** [comment]
I replaced all occurences of 'unread' to 'notselectedsinceload' in the file
CustomCSSforFx/classic/config/custom_tab_text_settings.css  

On my Firefox 61.0b11 (64-bit) Linux it triggers the colors, but on selection of the tab, it doesn't revert back to normal.

**Comment by Aris-t2** [comment]
Not sure, maybe its different on Linux, but inspecting tabs with developer tools on Windows don't show `notselectedsinceload` state. I know how to make unread tab appear on Firefox/Waterfox 56 for example, so that's not the issue. If the colors don't revert, its proven `notselectedsinceload` is not a replacement for `unread`.

**Comment by Aris-t2** [comment]
Removed "unread" references on latest updates.
