### ISSUE TITLE
Search Go Button is wrong color when using Oldsearch60.css

### ISSUE THREAD

**Issue by wedge1138** [Aris-t2/CustomCSSforFx#138]
When I apply the Oldsearch60.css and XML I noticed that the search go button was the wrong color when using the built-in dark theme.

I was able to correct it by making the following changes in the XML:

Old
<xul:hbox class="search-go-container">
          <xul:image class="search-go-button"
                     anonid="search-go-button"
					 onclick="handleSearchCommand(event);"
                     tooltiptext=" "/>

![bad](https://user-images.githubusercontent.com/42850729/44882545-a33c1480-ac68-11e8-81b5-59424c653840.PNG)

Updated
<xul:hbox class="search-go-container">
          <xul:image class="search-go-button urlbar-icon"
                     anonid="search-go-button"
					 onclick="handleSearchCommand(event);"
                     tooltiptext="Submit Search"/>

![good](https://user-images.githubusercontent.com/42850729/44882712-66245200-ac69-11e8-8b1c-55d56cd6124e.PNG)

I wanted to report this in case it should be corrected.  I am new to this so I wasn't sure if there was a better approach or other issues occurring.

Thank you to everyone for your hard work

5. System information
- OS & OS version: Win 10 1803
- OS theme name: Default
- DPI / HiDPI resolution:  1920X1080
- Firefox version: 61.0.2
- Firefox theme / lw-theme:  Dark Theme
- This projects settings the issue occurs with: Oldsearch60.css

**Comment by Aris-t2** [comment]
I have no idea why you see an _arrow_ instead of the _search glass_ set inside "Old Search" code.

![grafik](https://user-images.githubusercontent.com/6013569/44907294-b2c66680-ad17-11e8-85b0-b7a9ead0f96b.png)

I will fix the color of search engines dropdown arrow for "dark" theme and also the tooltip label on next update.

![grafik](https://user-images.githubusercontent.com/6013569/44907969-28333680-ad1a-11e8-8cd5-0758284e102f.png)

**Comment by Aris-t2** [comment]
2.0.4: https://github.com/Aris-t2/CustomCSSforFx/releases/

**Comment by wedge1138** [comment]
Thank you very much.  That helped me get it exactly the way I wanted it.
