### ISSUE TITLE
add this tweak- only one tab hide

### ISSUE THREAD

**Issue by blackcrack** [Aris-t2/CustomCSSforFx#155]
Hi,

i have found this page with the tweak for hide one tab, 
have short make a portable 63.0 with -profile ./profile
and have test this tweak.. and it works also on 63.0 !
is this allready added ? : 

https://gist.github.com/BenoitAverty/af633ee20e27f48f9ba7178451432206#gistcomment-2597605

win7 (but it should also work in linux)

best regards
Blacky

**Comment by Aris-t2** [comment]
Sorry, but that code is not working properly, because it only works, if the "new tab" button/tab is not on tabs toolbar.
The code in the link just hides the "new tab" button/tab.

**Comment by blackcrack** [comment]
so it's maybe a option to use, but it's not really hide a / the single tab in real and it is only a work around ?
you have more experiences about.. this is why i ask..

best regards
Blacky

**Comment by Aris-t2** [comment]
I tried this back then first before I added a JavaScript based feature to Classic Theme Restorer years ago. 
Nothing changed since then regarding the CSS solution. That is why I haven't added it to this project.

Hiding the tabs toolbar for only one visible tab has to also hide new tab tab/button. Otherwise the option is not valid enough in my opinion. If of course works fine for those, who remove the new tab tab/button from their tab toolbar anyway.
