### ISSUE TITLE
[Firefox 64+] 'Old Search' (xbl/xml based) won't work anymore due to internal Firefox changes! Use provided Javascript alternative!

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#158]
I don't know, if there is a workaround or fix yet, so if you know something, be my guest and share any info regarding the possibility of restoring the old search on Firefox 64+.

It looks Mozilla dropped the binding requirement for "searchbar" node. The old search however requires and modifies it, so it may be a good start to investigate there.

-----------------------

### JS based 'Alternative Searchbar' support thread: https://github.com/Aris-t2/CustomJSforFx/issues/11

![000](https://user-images.githubusercontent.com/6013569/50540551-2c6e4400-0b94-11e9-8e5a-1d519206a7e6.png)
![123](https://user-images.githubusercontent.com/6013569/50540552-2d9f7100-0b94-11e9-9314-b37a4d83b1c4.png)

Old (closed) thread: https://github.com/Aris-t2/CustomCSSforFx/issues/104

------------------------------------

If the old search is an essential feature you need and you got tired of Mozilla for removing features and the possibility to restore them, there is a great browser out there, that offers "the old search" by default.

[Vivaldi 2.6+](https://vivaldi.com/)
![vivaldi](https://user-images.githubusercontent.com/6013569/59961626-86fcb300-94da-11e9-850e-f1b750bb980a.png)

**Comment by tiansh** [comment]
I had created an web extension to address the searching behavior. It cannot modify the search bar. But you may switch search engine quickly and know which one is chosen currently. It is implemented by adding a fake search engine and redirect web requests to the search engine user chosen. And sadly, no search suggestions would be shown due to web extension limitation. GitHub repo for it is tiansh/classical-search-bar , and hope it would be helpful.

**Comment by Huusoku** [comment]
Signed up to GitHub just to say I wish I had the ability to help and not having Classic Search after the latest FF update has been difficult to live without. :( Considering returning to FF63...

**Comment by bendover22** [comment]
I'm not sure what exactly won't work to make the old "Find" (Search) at bottom of screen look like pre-Austrailus?  I've been using the same CSS code since Austrailus came out.  The size of Close buttom (X) or the padding / margin around elements or font size might need a little tweaking. 

It highlights all found instances & can show x out of y instances is now focused. 
But everything still works & it's all shifted to the left side, bottom of browser - like it used to be.
I'm sure not using any JS for it, unless you mean something completely different?
![image](https://user-images.githubusercontent.com/1909407/55676747-642a0d80-58a0-11e9-9d72-d75cbe3316fe.png)

**Comment by Aris-t2** [comment]
This thread is about the "search bar" (the bar with search engines like Google, Bing...., normally placed on navigation toolbar) not about the "findbar" which is for searching inside web pages.

**Comment by Aris-t2** [comment]
I think we can close this one now.
