### ISSUE TITLE
[Fx65] ac_popup_url_and_title_50percent_width.css - different results between Fx64 and Fx65?

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#181]
What do you mean with "too wide"?
The amount of space is calculated like this: take 100% of window width and subtract about 100px for the spaces (around&between icons, between url and text, at lines end) and icons and split whatever left.

_Originally posted by @Aris-t2 in https://github.com/Aris-t2/CustomCSSforFx/issues/180#issuecomment-458719799_

Issue left unsolved. Entire thing is still messy and doesn't work as intended.

With fix implemented (based on what Acid-Crash posted) it's still broken

http://prntscr.com/mdytz7

As written in comment to now (for some reason) closed topic - labels work incorrectly and so on compared to what was under same settings with FF64. Hope this screenshot illustrates well whats the issue.

**Comment by Acid-Crash** [comment]
It looks you are talking about a different feature.
So please take it easy calling it broken and questioning previous issue closure status.
Once more, **ac_popup_url_and_title_50percent_width.css** logic was the same since its introduction and didn't change in FF65.
Maybe you are referring to so called "old autocomplete popup" that used to have the same with as location-bar. Heard about is somewhere but didn't use is, so I don't have much insights on it.

**Comment by Nyekomimi** [comment]
Oh, no. I am 100% sure I used the one we talked of. Because I keep copying settings from old UserChrome to new one every update.

And dear god this autocomplete is so bloated and ugly. I need to get it fixed. (or, I guess, to get Firefox somehow rollbacked to 64...)

**Comment by Nyekomimi** [comment]
Checked the old autocomplete popup. That one *starts* in proper place but it's two-line instead of one-line. How do I fix that?

**Comment by Acid-Crash** [comment]
I am not questioning that you've are using **ac_popup_url_and_title_50percent_width.css**
The point is, that width change wight might have been made by a different style or a module that worked in conjunction with ac_popup_url_and_title_50percent_width.css

Take a look at initial issue template and try to fill all the mentioned details.

**Comment by Nyekomimi** [comment]
Oh, I see what you mean. However, as I said, I do no changes to such stuff from edition to edition. 

For now I guess I'll stick to the two-line autocomplete. The question is how to remove the unnesesary repetition? For example when it autocompletes the gmail first popup (with title and with url) shows exact same link. Tho it is auto-selected. Still, unnesesary bloat that interrupts a bit on monitor with 1024 height.

**Comment by Aris-t2** [comment]
The issue was closed as invalid, because nothing changed between Fx64 and Fx65 or at least there was no comparable screenshot of Firefox 64 and Firefox 65 with the same setup. I intend to close any new issue, that does not meet the provided instructions inside the [template](https://github.com/Aris-t2/CustomCSSforFx/blob/master/ISSUE_TEMPLATE), that is shown as soon one hits the "New issue" button.

Not sure what the markings on your screenshot (http://prntscr.com/mdytz7) are meant to show, but the result of an active **_ac_popup_url_and_title_50percent_width.css_** did not change between Fx64-67.

_Firefox 64_
![64](https://user-images.githubusercontent.com/6013569/51965895-2f967180-246b-11e9-9d34-5ef680876867.png)

_Firefox 65_
![65](https://user-images.githubusercontent.com/6013569/51965901-36bd7f80-246b-11e9-9b26-b1b74ddc794d.png)

_Firefox 66_
![66](https://user-images.githubusercontent.com/6013569/51965907-3b823380-246b-11e9-9f5f-c10bc14a49e7.png)

_Firefox 67_
![67](https://user-images.githubusercontent.com/6013569/51965914-3f15ba80-246b-11e9-9f37-f35abcb6649d.png)

-------

And here is how it looks on Fx65, if **_ac_popup_url_and_title_50percent_width.css_** is disabled (default appearance):

![65d](https://user-images.githubusercontent.com/6013569/51966103-e5fa5680-246b-11e9-8e1e-153ecd121721.png)

**Comment by Aris-t2** [comment]
This "issue" is not a real issue. Discussing features and options can be continued inside general discussion threads.

Replies in this thread are still possible too, even after closing it.
