### ISSUE TITLE
On addon detail view, buttons not shown on FF 72+ (and another thing)

### ISSUE THREAD

**Issue by techboyg5** [Aris-t2/CustomCSSforFx#297]
When you use the buttons instead of the menu popup on addons, the buttons are not shown on the details view on FF 72+ only. 71 and below were not affected.
The other thing is to show the text "Disable" instead of the toggle and put it to the left of Remove.

**Comment by Aris-t2** [comment]
> When you use the buttons instead of the menu popup on addons, the buttons are not shown on the details view on FF 72+ only. 71 and below were not affected.

I never looked into why the buttons are hidden on the details page as I considered this a feature. ;-)

> The other thing is to show the text "Disable" instead of the toggle and put it to the left of Remove.

This won't happen. The toggle item might not be the best solution, but it helps getting the other buttons where they are. Having a button containing a label with different size for each locale would only break button positions, because toggle button and the other buttons are not inside the same menu.
This was the main reason I removed the "Disable"/"Enable" labels inside themes area.

**Comment by Aris-t2** [comment]
Just looked into this. Removing "addon-list" tag from the code "restores" the buttons on details page.

**Comment by techboyg5** [comment]
> 
> 
> Just looked into this. Removing "addon-list" tag from the code "restores" the buttons on details page.

OK, then fix it.

**Comment by Aris-t2** [comment]
Already done. Fixed code will be present on next update.

**Comment by Aris-t2** [comment]
[==> v3.1.1](https://github.com/Aris-t2/CustomCSSforFx/releases)
