### ISSUE TITLE
Could someone compile something to fit these requested fixes?

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#37]
https://support.mozilla.org/en-US/questions/1185524

I'd be really grateful ^^'

![firefox_3_6](https://user-images.githubusercontent.com/6013569/33245738-04a7c6a6-d30c-11e7-9b3a-93aadc6023ed.png)

**Comment by Aris-t2** [comment]
Hi, its not how this project works.
I tried to port as many things from my Firefox add-ons as possible, but there never was a 100% matching Fx 3.6 ui.

You have to read through the features this project offers and enabled/disable the stuff you need manually.

You can do this from your screenshot
- tabs below other top toolbar
- custom tab width
- blue back/forward buttons
- custom toolbar icons
- rounded location/search bars
- smaller location bar (Customize mode > ui density)
- star button in location bar (by default)

**Comment by Nyekomimi** [comment]
Hi. My main problem is that I have trouble understanding what fits in what. That's why I can't do it well and why I asked for help.

**Comment by Aris-t2** [comment]
I think is better to guide people and encourage them to try things for themselves. That way future changes can easily be done without further external help.

First steps
1. extract the zip file from release area to your profiles chrome folder (see main page about how to do that)
2.  open/edit userChrome.css file with a text editor (Notepad++ recommended, but any will do)
3. search for the line `/* @import url(./css/tabs/tabs_below_navigation_toolbar.css); */`
4. remove `/*` and `*/`
5. repeat for
- `/* @import url(./css/buttons/custom_backforward_large_ff3_strata.css); */`
- `/* @import url(./css/buttons/icons_custom_icons.css); */`
- `/* @import url(./css/locationbar/locationbar_border_roundness.css); */`
6. search for the line `@import url(./css/buttons/icons_colorized.css);`
7. add `/*` and `*/`to it
8. save file and restart browser

Now you have completed first steps and modified you browser ui. Look through userChrome.css to find additional tweaks you might want to use.

**Comment by Nyekomimi** [comment]
...How to find that zip file? I opened classic folder and there is no zip there.

**Comment by Nyekomimi** [comment]
Someone linked me it.

Will get to making changes in morning, since its past midnight ^^'

**Comment by Nyekomimi** [comment]
Hi! Followed steps you suggested (except for leaving default icons, it seems good. Maybe will replace with new ones later)

Now, what files correspond to:

Pernamently removing new menu (3 bars button on right side of download button) - all of it's functionalities are already in File/Edit/View ect >_>

Reducing size of adress bar (and size of font in it)

Changing (modified) tabs bar into really light grey (what you gave me made it, and inactive bars, medium grey)

Changing transparent File/Edit/View bar into white?

And, most importantly, script to bring back pre-Quantum new tab so we don't have to rely on soon-to-be-removed legacy setting...

**Comment by Aris-t2** [comment]
Well, this project offers you some of the old stuff, but not a total conversion to Firefox 3.
If you really need that, I suggest to switch Seamonkey, install a Firefox 3 theme and some other add-ons, that can tweak the ui.

Back / forward look like that, because you previously set them like that "see custom back/forward buttons" area in userChrome.css.

As for the other icons, you need more toolbar icon variations to get other icons:
Replace ./image/toolbar_fx_mix.png
with one of these
![fx_toolbar_ff3](https://user-images.githubusercontent.com/6013569/32944643-895e938a-cb90-11e7-9f35-bb8a9830268c.png)
![fx_toolbar_ff3_strata](https://user-images.githubusercontent.com/6013569/32944644-897a783e-cb90-11e7-9b53-1309f3aec4f5.png)

**Comment by Aris-t2** [comment]
Most Firefox icon sets from Classic Toobar button add-on are now part of this project (v1.3,1).
The blue close icon from Firefox 3 will be added soon.

**Comment by Nyekomimi** [comment]
Yay!

One more thing... as I mentioned, this:
`#TabsToolbar {                                                                  
  background: #F9F9FA !important;                                             
  -moz-appearance: unset !important;                                          
}    `
Failed to work with how scripts are written, even if I placed it at very end. How to make inactive tabs + tab background ( http://prntscr.com/hca6yn ) colored light grey rather than transparent? (active tab is already light grey/white)

Also, is there way to make bottom line of tabs 1-2 pixels thicker? Lowermost line of color it currently have, 1-2 lines between it and tabs themselves of color of tabs background/inactive tabs?

**Comment by Aris-t2** [comment]
You most likely imported the wrong line. Tabs toolbar has a background color by default when using `@import url(./css/tabs/tabs_below_navigation_toolbar.css);`. [Make sure you are using the latest files.](https://github.com/Aris-t2/CustomCSSforFx/releases)

Tab colors can be set inside `/css/tabs/custom_colors_for_squared_tabs.css`. Edit this file and add custom colors instead of the predefined examples.

Add this to userChrome.css to increase tab toolbars bottom border in 'tabs not on top' mode:
```css
#TabsToolbar{
  border-bottom: 3px solid #5f7181 !important;
}
```

**Comment by Aris-t2** [comment]
Recent updates include Firefox 3.6 like tabs and toolbar colors. You have to enable them manually for tabs, menubar, tabs toolbar below navigation toolbar, general toolbars.

**Comment by Aris-t2** [comment]
The mentioned Firefox 3.6 ui is now almost completely replicable with recent releases. Have fun.

(You can still post in this thread even, if it is closed)
