### ISSUE TITLE
[Firefox 89][Proton] Tabs below navigation toolbar wrong height when many tabs opened

### ISSUE THREAD

**Issue by Atexor** [Aris-t2/CustomCSSforFx#373]
1. Describe the issue
Hello, I've installed latest FF v89 and noticed broken tabs so I updated CustomCSSforFX to latest using: `tabs_below_navigation_toolbar_fx89.css`
Hopefully tabs were below again, but noticed problem with tabs width and "+" button when there are many tabs opened.

2. What should have happened instead?
Tabs should be on the same height and "+" button should be smaller

3. Steps to reproduce the issue?
Just open many, many tabs

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![obraz](https://user-images.githubusercontent.com/34380553/120934972-efadbc00-c700-11eb-8aca-663d84daef3c.png)
![obraz](https://user-images.githubusercontent.com/34380553/120934978-f9cfba80-c700-11eb-8156-9cc916c3432d.png)

When there are less tabs it looks fine
![obraz](https://user-images.githubusercontent.com/34380553/120934989-07854000-c701-11eb-9b4d-b5645f60c9a6.png)

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]): yes
- OS & OS version:  Windows 10 20H2 
- OS theme (if not default):  Dark (side of the Force)
- DPI / HiDPI resolution:  1920x1080p
- Firefox version: 89.0
- Firefox theme / lw-theme:  Dark Gray Theme (WebExtension) / default dark
- Proton enabled (yes / no): by default yes
- This projects 'settings' the issue occurs with: n/a

PS. I really sincerely thank you for your work so far .

**Comment by yochaym** [comment]
hi aris,

this is the problem i've described in #344. which happens because the height of the tabstoolbar is affected by the toolbarbuttons placed on it (either when the tabs scrollbar buttons are showing or by adding buttons through customization). the solution you adopted from ichier does not address this issue and so does not solve the problem (the whole tabs_below_navigation_toolbar_fx89_LinWin_default_tabs is not needed). to solve the issue you need to reduce the --toolbarbutton-inner-padding value on the #TabsToolbar to anything below the value calculated in that post (the maximum makes it looks better on hoover)...

**Comment by yochaym** [comment]
hi aris,

this is the problem i've described in #344. which happens because the height of the tabstoolbar is affected by the toolbarbuttons placed on it (either when the tabs scrollbar buttons are showing or by adding buttons through customization). the solution you adopted from ichier does not address this issue and so does not solve the problem (the whole tabs_below_navigation_toolbar_fx89_LinWin_default_tabs is not needed). to solve the issue you need to reduce the --toolbarbutton-inner-padding value on the #TabsToolbar to anything below the value calculated in that post (the maximum makes it looks better on hover)...

**Comment by Aris-t2** [comment]
This did not work equally well for both default and classic tabs. Because of that I did not use the code at first.
I will look into it.
Thanks again.

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomCSSforFx/issues/380
