### ISSUE TITLE
Multiple tabs blank space on FF89 Proton

### ISSUE THREAD

**Issue by bembosh** [Aris-t2/CustomCSSforFx#388]
Hi.

I have an issue with multiple lines tabs.
If I enable Proton in FF89, I get extra space below tabs. It is not present if only one tab is open. If I open second or more tabs, I get this space.. and on the right there is visible scroll bar for tabs (even though only two tabs are open).
If I disble Proton, everything is fine.
Attached is the screenshot.

- latest CustomCSSforFx files 3.2.4
- Windows 10 Pro (20H2), x64bit
- Simply silver 2.0 theme (if I disable it, it is the same)

![blank space multiple lines tab FF89](https://user-images.githubusercontent.com/58531084/121921449-4cc8f380-cd39-11eb-9c4d-98be37290ac0.jpg)

**Comment by Aris-t2** [comment]
Please use the corresponding issue/thread: https://github.com/Aris-t2/CustomCSSforFx/issues/39

Tabs below navigation toolbar and multiple tab lines only work together, if you use tabs_below_navigation_toolbar_fx65_v2.css and tabs_multiple_lines_fx81.css.

**Comment by bembosh** [comment]
For me it doesn't work.
After your post, I rechecked my userchrome.css and I already had tabs_below_navigation_toolbar_fx65_v2.css and tabs_multiple_lines_fx81.css
Then I cleared fully my userchrome.css and added just those two. Still didn't work.
Then I followed 3.2.7's guideliness from multiple_tab_lines.css from Proton folder - and used only that code in userchrome.css - and still nothing. It doesn't even works as multiple lines.
I'll wait for some further development. 
Thanks for your work on this, I appreciate your efforts to make users life happier.

**Comment by Aris-t2** [comment]
I can not test all possible configurations, but the default one with tabs_below_navigation_toolbar_fx65_v2.css and tabs_multiple_lines_fx81.css gives me this result, even on Fx 91 Nightly:

![image](https://user-images.githubusercontent.com/6013569/121960255-22415f80-cd66-11eb-8179-574ca365d2b9.png)

**Comment by Ruffz** [comment]
I had this extra space too and found that was caused by line 20 in "tabs_multiple_lines_fx81.css"

`--tab-min-height_mlt: var(--tab-min-height,32px); /* set own value here, if used without configuration files */`

If I "/*" this line, it's fixed.

It's seems this variable is missing in config folder.

**Comment by bembosh** [comment]
> 
> 
> I had this extra space too and found that was caused by line 20 in "tabs_multiple_lines_fx81.css"
> 
> `--tab-min-height_mlt: var(--tab-min-height,32px); /* set own value here, if used without configuration files */`
> 
> If I comment this line (with /*) , it's fixed.

Thanks for the tip @Ruffz ,
however for some reason, this also doesn't work for me. Luckily, I still have the option to disable Proton and everything is fine. For now.

**Comment by bendover22** [comment]
I hadn't updated Custom CSS in a while.  My linux Mint 20, 64 bit box was still fine for multirow tabs - no extra spaces above / below 1st tab row.
Another linux box, Mint 19.3 - **32 bit**, had the extra space above & below tabs.  Tabs were always above nav bar.

Today I updated the Mint 19.3, 32 bit box to Custom CSS v3.3.2.1.
I always had **linear gradients** on tabs (from my_userChrome), which worked until switching to CSS v3.2.2.1. Different gradients for selected, not selected, & hovered tabs.
**MAIN problem now is, can't get my gradients for not-selected or hovered tabs to work.  

After importing tabs_multiple_lines.css (actually tried a couple versions - for Fx 81+), gradients ONLY on **selected tab still worked.**  All other tabs BG color changed to weird brown, small variation linear gradient, just like shown in https://github.com/Aris-t2/CustomCSSforFx/issues/388#issuecomment-860999254.  Except there were **no brown tabs** on any apps, before updating CustomCSS, even though Fx 90 was installed.

I never found where the brown came from.  I never hit on the right selector to use in my_userChrome, to change not-selected tabs BG.  I tried a bunch.  I suspect something about Proton, or in Custom CSS interfered w/ changing not-selected tabs BG.
Because **after I disabled** CustomCSS totally, the gradients in my_userChrome worked - w/ the same selector syntax & properties for **not-selected** tabs that I'd been using for a year or more.

Except now, Proton (I guess) makes the tabs huge - 44px high. :)  I imagine I can control the tabs height easy enough.  Nothing in my_userChrome would make them that high, AFAIK.  Also tried a couple of CustomCSS classic_squared_tabs.css, classic_squared_tabs_australized.css.
All the CustomCSS  "default_tabs..." files have same modified date. 

 Not sure if using another tab file would make a difference, like "**default_tabs_tab_background_appearance.css**" or "**default_tabs_enhanced.css**?"

In the screen (no CustomCSS being used), tabs = 44px high, BUT my gradients work.
![fx 90-huge tabs w-o custom CSS--or editing in userChrome-2021-7-26](https://user-images.githubusercontent.com/1909407/127096506-be44eac6-0aa7-4929-9b23-aad3eb7450ea.png)
