### ISSUE TITLE
Which options in current CustomCSS replaced some legacy features?

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#437]
Hello! This is low priority, not a bug.

I am looking for following option replacements:
@import "./css/locationbar/icons_colorized.css"; /**/
@import "./css/locationbar/identitybox_replace_i_icon_with_globe.css";
@import "./css/locationbar/pageaction_separator_in_location_bar_hidden.css"; /**/
@import "./css/locationbar/starbutton_is_last_pageaction_button.css"; /**/

As autistic person I prefer to keep stuff same, despite Mozillas insistence on making stuff uglier. So the CSS is a lifesaver, tyvm for that! The moment the above stuff is answered, all should be great again <3

**Comment by Aris-t2** [comment]
Hi,

I understand keeping the ui mostly untouched between Firefox versions is the goal here.

To be honest I do not remember why the first option did not make the jump to CustomCSSforFx v4.x, but the others got dropped, because the i-icon and the separator got removed from Firefox and the star button became the last one by default.

`icons_colorized.css`  will be restored on next update and `identitybox_replace_i_icon_with_globe.css` will return  as `identitybox_replace_search_icon_with_globe.css` on next update.

**Comment by Nyekomimi** [comment]
Tyvm!

**Comment by Aris-t2** [comment]
Use this dev build to restore the mentioned settings:
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.4pre
