### ISSUE TITLE
Add thin tabs configuration

### ISSUE THREAD

**Issue by unv-unv** [Aris-t2/CustomCSSforFx#52]
Firefox 57 would ignore browser.tabs.tabMinWidth settings below 50 px (in previous versions it didn't ignore small values). This can be only be overridden in userChrome.css.

Please add option for thin tabs (for example, I use 12px so scrollbar doesn't appear in case of many tabs open).

**Comment by userOperaFF** [comment]
Maybe buggy, in try this in Firefox 57 nightly  (long time ago) cards shifted to right (1 or 2 cards width).

**Comment by Aris-t2** [comment]
Settings custom tab min width already is there in "tab_maxwidth.css" file unofficially.
Since Firefox tabs behave weirdly sometimes lower values than 5050 may break the ui, but you are welcome to experiment.

Open "tab_maxwidth.css" und revome `/*` you know where.

https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tab_maxwidth.css

**Comment by unv-unv** [comment]
Yes, I indeed already uncommented tab_maxwidth.css and set there min-width before creating this feature request :)

**Comment by Aris-t2** [comment]
Good to hear.
