### ISSUE TITLE
Flexible Spaces

### ISSUE THREAD

**Issue by enthusiast01** [Aris-t2/CustomCSSforFx#578]
Firefox changed flexible spaces long ago. There used to be a large and a small space. With the new direction, they removed the small space. Is it possible to modify the min size of the flexible space? All the scripts I found do not work.

**Comment by enthusiast01** [comment]
The CSS workaround like the 5 other ones I have tried do not work, sadly.

The https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/space_and_separator_restorer.uc.js - I assume I need to use some kind of script addon like greasemonkey, copy the contents of that link into it?

**Comment by krystian3w** [comment]
No, these scripts are not installed to any GreasyMonkey/Tampermonkey/ViolentMonkey.

You need to prepare a browser profile according to method 2: https://github.com/Aris-t2/CustomJSforFx#method-2---files-in-install-and-profile-folders

And there find the file "userChrome.js" in which you enter the scripts for activation (Line 2-3: https://github.com/Aris-t2/CustomJSforFx/blob/82fc2357524da1f98d4e19a6506eeb460f98a9b6/method%202/profile/userChrome.js#L2-L3).

Then the narrow space appears in the standard customization mode (need restart (not "reset") Firefox).

----

And I think I've figured out what it is about not working. Depending on how stuffed the bar is, that's how poorly the number will work - you can test a few in the 1-100 range.

I haven't checked how it works in Firefox 113, maybe there it doesn't depend so much on stuffing in a particular bar anymore.

Or you're so helpless that you don't know what to replace "`#unique-element`" with correct "name" of element https://github.com/Aris-t2/CustomCSSforFx#how-to-find-item-ids-and-attributes (I prefer to change a single space instead of knocking them all down, so then you have to replace the element name).

**Comment by enthusiast01** [comment]
Overly complicated for the request. Took a while to find it, but this suits my need just fine:

/* Make Flexible Space into Fixed Space */
toolbarspring {
    min-width: 10px !important;
    max-width: 10px !important;
}

Change 10px to whatever works best.

**Comment by krystian3w** [comment]
I still prefere extend editor in  customization mode, somewhere I like flex.
