### ISSUE TITLE
[Windows Classic OS theme] Bookmarks popup transparent

### ISSUE THREAD

**Issue by nedriv** [Aris-t2/CustomCSSforFx#60]
Win7 Fx57
I am using 1.3.0 version of CTR css and related files.  I have made No edits to the files.
When I click the Bookmarks icon on the toolbar, the popup shows all bookmarks, but the background is transparent.  When I Rename the userChrome.css and restart Fx57.0, the bookmarks popup is displayed with white background.
![picture0001](https://user-images.githubusercontent.com/33789065/32983391-a07cd744-cc48-11e7-8a9b-e70ee6cb855d.jpg)

Regards,
EdV

**Comment by Aris-t2** [comment]
Thanks for pointing this out. Mozillas Windows Classic theme support ran out a long time ago. Many things look wrong even, if set correctly in css.

After Mozilla dropped supporting @media rules for different OS themes, some options require additional files.

Download version 1.3.1 and modify userChrome.css.
Search for `bookmarks_menu_button_popup_classic_appearance_windows_classic.css` and enable that one instead of `bookmarks_menu_button_popup_classic_appearance.css`.

**Comment by nedriv** [comment]
@Aris-t2 
Thanks for the quick fix.  It works perfectly!
