### ISSUE TITLE
[tabs not on top] Pinned tabs get hidden in overflow mode (bug with Firefox view button on tabs toolbar)

### ISSUE THREAD

**Issue by Infernoflower** [Aris-t2/CustomCSSforFx#629]
1. Does the issue occur without any files inside /chrome/ folder?
No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
When I updated to Firefox 119, I discovered that my pinned tabs disappeared when I had 17 or more tabs open after the
pinned tab. It happens when I turn on This happens when I turn on /* Windows/Linux */@import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ in userChrome.css.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, but there might be an option in the latest version to fix this. Not sure though. 

4. Screenshots showing the issue (drag & drop images into this post):

![Pinned Tabs Problem 1](https://github.com/Aris-t2/CustomCSSforFx/assets/33663759/6f95dcc0-c530-491a-8b64-e798ae0fe135)

![Pinned Tabs Problem 2](https://github.com/Aris-t2/CustomCSSforFx/assets/33663759/d6567c72-b210-4fb9-8f09-170d15f4e1d3)

![Pinned Tabs Problem 3](https://github.com/Aris-t2/CustomCSSforFx/assets/33663759/609a4bdf-e060-438a-9ad3-73f960ca8022)

5. System information

- OS & OS version: Windows 10 Home, version 22H2
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 119.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): default

**Comment by Aris-t2** [comment]
I can not reproduce this.

Latest version, only enabled `tabs_below_navigation_toolbar.css`. Tested on Fx 119 and 121 with up to 50 tabs.

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/4f677188-d407-4a3c-bfa4-49ea76bcc860)

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/394bdf27-c9a8-41d1-85ab-1f37411649f8)

Try vanilla setup and only enable `tabs_below_navigation_toolbar.css`.

**Comment by ImSpecial** [comment]
FYI: Getting the game issue, came to report but it looks like OP beat me to it.

I'm still trying to figure if there is something "more" to the glitch, but yeah, if I have 2 or 3 pinned tabs, then open and keep opening addition unpinned tabs, eventually the overflow of tabs will make the pinned tabs vanish and then the tabs all dance around and go wonky until I close some of the tabs to prevent the overflow. (if that makes sense...)

**Comment by Aris-t2** [comment]
May its some specific combination. Tested vanilla setup with "default_tabs_photon_alt.css".


https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/b44e89ae-9e65-411c-9f8e-d3d68c243784

**Comment by ImSpecial** [comment]
My attempt at a gif to showcase.

![Animation](https://github.com/Aris-t2/CustomCSSforFx/assets/4022372/3fa09287-bedb-4c43-89be-07e08d9aeafe)

**Comment by ImSpecial** [comment]
One thing of note that I just recently noticed, is that none of these issues happen in a Private Window Mode...

Tabs, pinned or not, all seems to behave properly in a Private Window.

**Comment by MarkRH** [comment]
Decided to test this and I can make the pinned tab disappear if I add enough tabs to cause the left/right scrolling arrows to appear.  If I close enough tabs to make the left/right arrows disappear, then the pinned tab comes back.  Will try some more testing.

Like ImSpecial, using a Private Window does not cause it to happen.  The pinned tab stays to the left of the left arrow. Will check some things..

**Comment by MarkRH** [comment]
I got it working in my normal profile.  I went to Customize Toolbar and I noticed a Firefox logo on the far left of the tab toolbar that was normally not visible.  Turns out it was for Firefox View.  I moved that button to the overflow menu.

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/8035962/fa2f8924-d203-43e6-aef3-90a023da3403)

Now, the pinned tabs always stay visible to the left of the navigation arrow when it appears.  

So, might see if you have anything showing to the left of the pinned tabs when customizing the toolbar.

**Comment by ImSpecial** [comment]
What the literal f*** Mozilla. I couldn't even see that "Firefox View" in the Customize Window... I needed to rename my chrome folder first, in order to restart Firefox back to its default layout, so that I could see it, then remove it.

Either way, removing that seemed to have fixed everything, and your a damn genius for figuring that out.

**Comment by MarkRH** [comment]
I noticed that the "Firefox View" thing only showed in Customize Toolbar if I did not have too many tabs open.  If I had too many tabs open, then it did not appear in Customize Toolbar.  Weird.

**Comment by Infernoflower** [comment]
Thanks for all your suggestions. I'll try them out.

**Comment by Aris-t2** [comment]
The visibility issue regarding the "Firefox view" button was caused by me.
I posted new files, where the button won't be hidden anymore by default, so everybody can move it from tabs toolbar to another toolbar in customizing mode.

[Custom CSS tweaks for Firefox v4.4.3**v3**](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by Infernoflower** [comment]
Thanks.

**Comment by adam-olson** [comment]
4.4.3v3 didn't work for me to fix the issue. Had to disable, @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ , before I could see the pinned tabs and use customize to remove the Firefox View tab and switch back on tabs below, then it looks good.

**Comment by Aris-t2** [comment]
@adam-olson 
Sorry, I don't know how to solve this for you.

**Comment by Aris-t2** [comment]
Test [v4.4.5 release](https://github.com/Aris-t2/CustomCSSforFx/releases/).

**Comment by Aris-t2** [comment]
Fixes since 4.4.5 release.
[4.4.6 release](https://github.com/Aris-t2/CustomCSSforFx/releases) is out too.
