### ISSUE TITLE
RE: bookmarks_toolbar_multiple_lines.css

### ISSUE THREAD

**Issue by alexandrefierro** [Aris-t2/CustomCSSforFx#67]
Greetings:

Where exactly is this CSS code supposed to be placed on Mac OS X ? The online documentation does not provide explicitly the actual path. I placed this css code inside:
"/Users/myusername/Library/Application\ Support/Firefox/Profiles"
but Firefox 57 (quantum) fails to load it.
Rationale for reverting to a CSS file is that most of my add-ons are no longer compatible on quantum and I do not have admin privilege on my work machine to downgrade Firefox to version 56 (as I've done in all my other machines, for now).

Cheers and many thanks for any help/tip you can provide,

Alex-

**Comment by alexandrefierro** [comment]
I just figured it out: I places the bookmark css code in

/Users/myusername/Library/Application\ Support/Firefox/Profiles/Chrome

within any already existing file named userChrome.css

Cheers and thanks,

**Comment by Aris-t2** [comment]
The main page offers a shot description on how to find profile folder through about:support page: https://github.com/Aris-t2/CustomCSSforFx/#where-to-find-firefox-profile-folder-and-what-is-the-correct-location-for-user-styles

I wasn't aware of the actual macOS/OSX path, because it changed a couple of time over the past few years.

Thanks for providing an updated path.
