### ISSUE TITLE
Firefox 57 ?

### ISSUE THREAD

**Issue by sportman40** [Aris-t2/CustomCSSforFx#78]
I am a disabled person do not know how to set up Firefox 57 to look like this screenshot click theme can someone please assist me get back to me please

<img width="447" alt="firefox colors" src="https://user-images.githubusercontent.com/34138498/33449602-45d4f7de-d5d7-11e7-8efa-c0ce42c09aec.PNG">

**Comment by Aris-t2** [comment]
You will have to download the latest release of this project and follow the instructions on main page on how to add files to your Firefox profile. Afterwards you need to edit userChrome.css file to enable/disable the settings you need.

Not everything on your screenshot is possible (if you really want the above ui, you might want to try Seamonkey browser instead of Firefox 57).
- sidebars top area does not look like this 
- search bar does not look like this
- there is no "go" button on toolbars
- there is no "activity indicator" for toolbars
- there are no "back/forward" history dropmarkers after back and forward buttons
- there is no add-bar on windows bottom, but one can be simulated


- download latest release (custom_css_for_fx_v1.4.x.zip) from here: https://github.com/Aris-t2/CustomCSSforFx/releases
- follow instruction from here (point 1-3): https://github.com/Aris-t2/CustomCSSforFx#where-to-find-firefox-profile-folder-and-what-is-the-correct-location-for-user-styles
- open userChrome.css in a text editor (Notepad++ suggested on Windows)
- you will have to enable/disable setting by removing and adding `/*` before `@imports`
- add `/*` before
  - `@import url(./css/buttons/buttons_on_navbar_classic_appearance.css); /**/`
  - `@import url(./css/buttons/icons_colorized.css); /**/`
  - `@import url(./css/tabs/classic_squared_tabs.css); /**/`
  - `@import url(./css/tabs/tab_close_always_visible.css); /**/`
  - `@import url(./css/toolbars/general_toolbar_colors.css); /**/`
- remove `/*` before
  - `/* @import url(./css/buttons/icons_custom_icons_fx2.css); /**/`
  - `/* @import url(./css/buttons/custom_backforward_large_ff2.css); /**/`
  - `/* @import url(./css/buttons/appbutton_hidden.css); /**/`
  - `/* @import url(./css/tabs/classic_squared_tabs_classic_grey.css); /**/`
  - `/* @import url(./css/tabs/classic_squared_tabs_fully_squared.css); /**/`
  - `/* @import url(./css/tabs/tabs_below_navigation_toolbar_classic_grey.css); /**/`
  - `/* @import url(./css/tabs/tab_close_hidden.css); /**/`
  - `/* @import url(./css/generalui/close_icon_red.css); /**/`
  - `/* @import url(./css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css); /**/`
  - `/* @import url(./css/toolbars/menubar_color_classic_grey.css); /**/`
  - `/* @import url(./css/toolbars/general_toolbar_colors_classic_grey.css); /**/`
- install tab close button on tabs toolbar add-on: https://addons.mozilla.org/addon/close-tab-button-quantum/

Use the general support thread for any questions regarding this project: https://github.com/Aris-t2/CustomCSSforFx/issues/41
